print('XUÂN VỀ')
print('Từng đàn con trẻ chạy xun xoe')  
print('Mưa lạnh, trời quang, nắng mới hoe')
print('Lá nõn nhành non, ai tráng bạc?')
print('Gió về từng tận, gió bay đi...')
print('Thong thả dân gian nghỉ việc đồng')
print('Lúa thì con gái mượt như nhung')
print('Đầy vươn hoa bưởi, hoa cam rụng')
print('Ngào ngạt hương bay, bướm vẽ vòng')
print('Trên đường cát mịn, một đôi cô')
print('Yếm đỏ, khăn thâm, trẩy hội chùa')
print('Gậy trúc dắt bà già tóc bạc')
print('Tay lần tràng hạt, miệng nam mô.')