print("/*****************************************/")
print("/******* HUONG DAN CHEP TAP TIN *******/")
print("/=>B1. Vao thu muc “C:\TUYENTAP\thotinh.txt”/")
print("/=>B2. Click chuot phai vao tap tin thotinh.txt /")
print("/=>B3. Chon copy tu menu tat /")
print("/=>B4. Chon vi tri can luu, click phai chon paste /")
print("/*****************************************/")